name: "Add Release Notes from Pull Request Commits"
description: 'Creates Release Notes from the commits of a Pull Request, and adds them to the body of the pull request.' 
inputs:
  pull_number:
    description: "The number of the PR to generate notes for. You only need to specify this if you're calling from an event other than pull_request"
    required: true
    default: ${{ github.event.pull_request.number }}
  token:
    description: "A GITHUB_TOKEN or Personal Access Token that is scoped to allow editing pull requests"
    required: true
  labels:
    description: "A comma-delimited list of labels that should be used as headings. If none are provided, changes will be labeled as 'Improvements'"
    required: false
runs:
  using: 'node16'
  main: 'notes.js'
